import type { TemplateContext } from '../types.ts';

export function renderOperations(ctx: TemplateContext): string {
  const { naming, entities } = ctx;

  const entityQueries = entities
    .map(
      (e) => `
// ── ${e.entityDisplayName} ──────────────────────────────────────────────────

export const GET_${e.entityType.toUpperCase()} = graphql(\`
  query Get${e.entityPascal}($uri: String!) {
    ${e.entityCamel}(uri: $uri) {
      id
      title
      status
      description
      createdAt
      updatedAt
    }
  }
\`);

export const GET_${e.entityType.toUpperCase()}S = graphql(\`
  query Get${e.entityPascal}s($query: String, $limit: Int) {
    ${e.entityCamel}s(query: $query, limit: $limit) {
      id
      title
      status
      updatedAt
    }
  }
\`);`,
    )
    .join('\n');

  return `/**
 * ${naming.displayName} Plugin GraphQL Operations.
 *
 * All queries and mutations used by the plugin's UI are defined here.
 * Types are auto-generated by graphql-codegen from the schema.
 *
 * Run \`pnpm codegen\` after schema changes to regenerate types.
 */

import { graphql } from './generated/gql';
${entityQueries || '\n// TODO: Add your GraphQL operations here'}
`;
}
