/**
 * Client exports — renderer-safe imports.
 *
 * @module graphql/client
 */

export { ApolloProvider } from '@apollo/client/react';
export { useQuery, useMutation, useLazyQuery, useApolloClient } from '@apollo/client/react/hooks';
export { default as gql } from 'graphql-tag';

export { createIpcLink } from './ipc-link';
export type { GraphQLExecuteFn } from './ipc-link';

export { createApolloClient } from './create-client';
export type { IpcGraphQLExecuteFn } from './create-client';

export { typePolicies, invalidateEntity, updateCachedEntity } from './cache-config';

export {
  // Project
  GET_PROJECTS,
  GET_PROJECT,
  CREATE_PROJECT,
  UPDATE_PROJECT,
  DELETE_PROJECT,
  // Workstream CRUD
  GET_WORKSTREAMS_BY_PROJECT,
  GET_WORKSTREAM,
  GET_ARCHIVED_WORKSTREAMS,
  CREATE_WORKSTREAM,
  FORK_WORKSTREAM,
  UPDATE_WORKSTREAM,
  ARCHIVE_WORKSTREAM,
  UNARCHIVE_WORKSTREAM,
  PIN_WORKSTREAM,
  UNPIN_WORKSTREAM,
  DELETE_WORKSTREAM,
  // Workstream agent commands
  SEND_WORKSTREAM_MESSAGE,
  STOP_WORKSTREAM_AGENT,
  RESTART_WORKSTREAM_AGENT,
  RESPOND_WORKSTREAM_PERMISSION,
  REVOKE_PERMISSION_RULE,
  INTERRUPT_WORKSTREAM_AGENT,
  CLEAR_WORKSTREAM_CONVERSATION,
  REWIND_WORKSTREAM_CONVERSATION,
  COMPACT_WORKSTREAM_CONVERSATION,
  SET_WORKSTREAM_IN_FOCUS,
  REPLAY_WORKSTREAM_HISTORY,
  LOAD_MORE_WORKSTREAM_HISTORY,
  IS_WORKSTREAM_AGENT_RUNNING,
  GET_USER_MESSAGE_HISTORY,
  // Workstream data ops
  GET_WORKSTREAM_LINKED_ENTITIES,
  GET_WORKSTREAM_DIRECTORIES,
  SWITCH_WORKSTREAM_MODEL,
  LINK_WORKSTREAM_ENTITY,
  UNLINK_WORKSTREAM_ENTITY,
  SET_LINKED_ENTITY_CONTEXT_OVERRIDE,
  GET_WORKSTREAMS_BY_ENTITY,
  RESOLVE_LINKED_ENTITY_CONTEXT,
  ENTITY_SEARCH,
  ADD_WORKSTREAM_DIRECTORY,
  REMOVE_WORKSTREAM_DIRECTORY,
  // Project directories
  GET_PROJECT_DIRECTORIES,
  ADD_PROJECT_DIRECTORY,
  REMOVE_PROJECT_DIRECTORY,
  // Routine
  GET_ROUTINES,
  GET_ROUTINES_BY_PROJECT,
  GET_ROUTINE,
  GET_ROUTINE_BY_WORKSTREAM,
  GET_ROUTINE_RUN_HISTORY,
  GET_ROUTINE_LATEST_RUN,
  CREATE_ROUTINE,
  UPDATE_ROUTINE,
  DELETE_ROUTINE,
  PAUSE_ROUTINE,
  RESUME_ROUTINE,
  RUN_ROUTINE_NOW,
  // Generic entity
  GET_ENTITY,
  GET_ENTITIES,
  SEARCH_ENTITIES,
  GET_ENTITY_TYPES,
  GET_ENTITY_MUTATION_CATALOG,
  // Group directories & branch selections
  GET_GROUP_DIRECTORIES_WITH_BRANCHES,
  ADD_GROUP_DIRECTORY,
  REMOVE_GROUP_DIRECTORY,
  SET_GROUP_BRANCH_SELECTION,
  REMOVE_GROUP_BRANCH_SELECTION,
  UPDATE_GROUP_AUTO_CREATE_WORKTREES,
  ARCHIVE_WORKSTREAM_GROUP,
  // Group CRUD
  GET_WORKSTREAM_GROUPS_BY_PROJECT,
  CREATE_WORKSTREAM_GROUP,
  UPDATE_WORKSTREAM_GROUP,
  PIN_WORKSTREAM_GROUP,
  UNPIN_WORKSTREAM_GROUP,
  DELETE_WORKSTREAM_GROUP,
  ADD_WORKSTREAM_TO_GROUP,
  REMOVE_WORKSTREAM_FROM_GROUP,
  LINK_GROUP_ENTITY,
  UNLINK_GROUP_ENTITY,
  GET_GROUP_LINKED_ENTITIES,
  // Branch selections
  GET_BRANCH_SELECTIONS,
  GET_DIRECTORIES_WITH_BRANCH_INFO,
  SET_BRANCH_SELECTION,
  REMOVE_BRANCH_SELECTION,
  // Git operations
  IS_GIT_REPO,
  GET_GIT_BRANCHES,
  GET_GIT_CURRENT_BRANCH,
  GET_GIT_DEFAULT_BRANCH,
  // Git diff operations
  GET_GIT_DIFF_SUMMARY,
  GET_GIT_WORKING_TREE_SUMMARY,
  GET_GIT_COMMIT_LOG,
  GET_GIT_COMMIT_DIFF,
  GET_GIT_BRANCH_DIFF,
  GET_GIT_WORKING_TREE_DIFF,
  GET_GIT_STATUS_FILES,
  GET_GIT_FILE_DIFF,
  GET_GIT_FILE_AT_REF,
  // Settings
  GET_SETTINGS,
  UPDATE_APPEARANCE_SETTINGS,
  UPDATE_AI_SETTINGS,
  UPDATE_ADVANCED_SETTINGS,
  UPDATE_SETTINGS_RAW,
  UPDATE_PERMISSIONS_SETTINGS,
  // Notifications
  GET_NOTIFICATION_SOURCES,
  SET_NOTIFICATION_SOURCE_MUTED,
  SET_NOTIFICATION_TYPE_MUTED,
  RESET_NOTIFICATION_MUTES,
  GET_PERMISSION_POLICY,
  SET_PERMISSION_POLICY,
  DELETE_PERMISSION_POLICY,
  GET_RESOLVED_PERMISSIONS,
  GET_RESOLVED_PARENT_PERMISSIONS,
  // Registry
  GET_REGISTRIES,
  GET_REGISTRY,
  GET_REGISTRY_QUICK_ACTIONS,
  GET_REGISTRY_QUICK_ACTION_DEFAULTS,
  GET_REGISTRY_VERIFICATION_ACTIONS,
  GET_REGISTRY_VERIFICATION_ACTION_DEFAULTS,
  ADD_REGISTRY,
  REMOVE_REGISTRY,
  UPDATE_REGISTRY,
  SYNC_REGISTRIES,
  // Command palette
  GET_COMMANDS,
  EXECUTE_COMMAND,
  RESCAN_CLAUDE_COMMANDS,
  // Permission templates
  GET_PERMISSION_TEMPLATES,
  GET_PERMISSION_TEMPLATE,
  CREATE_PERMISSION_TEMPLATE,
  UPDATE_PERMISSION_TEMPLATE,
  DELETE_PERMISSION_TEMPLATE,
  APPLY_PERMISSION_TEMPLATE,
  // Skills
  GET_INSTALLED_SKILLS,
  GET_REGISTRY_SKILLS,
  INSTALL_SKILL,
  UNINSTALL_SKILL,
  UPDATE_SKILL,
  ACTIVATE_SKILL,
  TOGGLE_SKILL_ENABLED,
  TOGGLE_SKILL_PINNED,
  SYNC_LOCAL_SKILLS,
  // Plugins
  GET_INSTALLED_PLUGINS,
  GET_REGISTRY_PLUGINS,
  INSTALL_PLUGIN,
  UNINSTALL_PLUGIN,
  UPDATE_PLUGIN,
  TOGGLE_PLUGIN_ENABLED,
  // Tags
  GET_TAGS_BY_PROJECT,
  GET_TAG_BY_NAME,
  GET_WORKSTREAM_TAGS,
  CREATE_TAG,
  UPDATE_TAG,
  DELETE_TAG,
  APPLY_TAG_TO_WORKSTREAM,
  REMOVE_TAG_FROM_WORKSTREAM,
  // Content Profiles
  GET_CONTENT_PROFILES,
  GET_ACTIVE_CONTENT_PROFILE,
  FORK_CONTENT_PROFILE,
  SWITCH_CONTENT_PROFILE,
  DELETE_CONTENT_PROFILE,
  // Tasks
  GET_TASK,
  GET_TASKS,
  GET_TASK_LABELS,
  CREATE_TASK,
  UPDATE_TASK,
  DELETE_TASK,
  CREATE_TASK_LABEL,
  UPDATE_TASK_LABEL,
  DELETE_TASK_LABEL,
  // Inbox
  GET_INBOX_ITEMS,
  GET_INBOX_UNREAD_COUNT,
  PUSH_INBOX_ITEM,
  MARK_INBOX_ITEM_READ,
  MARK_ALL_INBOX_ITEMS_READ,
  ARCHIVE_INBOX_ITEM,
  DELETE_INBOX_ITEM,
  EXECUTE_INBOX_ACTION,
  // Events
  GET_REGISTERED_EVENTS,
  // Entity Tool (dev)
  GET_ENTITY_TOOL_ENTRIES,
  ADD_ENTITY_TOOL_ENTRY,
  REMOVE_ENTITY_TOOL_ENTRY,
} from './operations';

export { useWorkstreamLinker } from './use-workstream-linker';
export type {
  UseWorkstreamLinkerOptions,
  WorkstreamLinkerResult,
  LinkerLinkedWorkstream,
  LinkerActiveWorkstream,
} from './use-workstream-linker';
