/**
 * GraphQL Operations — Typed document nodes for all queries and mutations.
 *
 * These are the operations used by renderer components via Apollo hooks.
 * Each operation is a TypedDocumentNode generated by graphql-codegen,
 * providing full type inference for variables and result data.
 *
 * Run `pnpm codegen` after schema changes to regenerate types.
 *
 * @module graphql/client/operations
 */

import { graphql } from './generated/gql';

// ─────────────────────────────────────────────────────────────────────────────
// Project Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_PROJECTS = graphql(`
  query GetProjects {
    projects {
      id
      name
      createdAt
      updatedAt
    }
  }
`);

export const GET_PROJECT = graphql(`
  query GetProject($id: ID!) {
    project(id: $id) {
      id
      name
      createdAt
      updatedAt
      workstreams {
        id
        title
        status
        isPinned
        messageCount
        lastActivityAt
      }
    }
  }
`);

export const CREATE_PROJECT = graphql(`
  mutation CreateProject($input: CreateProjectInput!) {
    createProject(input: $input) {
      id
      name
      createdAt
      updatedAt
    }
  }
`);

export const UPDATE_PROJECT = graphql(`
  mutation UpdateProject($id: ID!, $input: UpdateProjectInput!) {
    updateProject(id: $id, input: $input) {
      id
      name
      updatedAt
    }
  }
`);

export const DELETE_PROJECT = graphql(`
  mutation DeleteProject($id: ID!) {
    deleteProject(id: $id)
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Workstream Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_WORKSTREAMS_BY_PROJECT = graphql(`
  query GetWorkstreamsByProject($projectId: ID!) {
    workstreamsByProject(projectId: $projectId) {
      id
      title
      status
      model
      isPinned
      isRoutineWorkstream
      groupId
      messageCount
      lastActivityAt
      createdAt
      updatedAt
      inFocus
    }
  }
`);

export const GET_WORKSTREAM = graphql(`
  query GetWorkstream($id: ID!) {
    workstream(id: $id) {
      id
      title
      status
      model
      isPinned
      messageCount
      lastActivityAt
      createdAt
      updatedAt
      project {
        id
        name
      }
    }
  }
`);

export const GET_ARCHIVED_WORKSTREAMS = graphql(`
  query GetArchivedWorkstreams($projectId: ID!) {
    archivedWorkstreams(projectId: $projectId) {
      id
      title
      status
      messageCount
      archivedAt
      updatedAt
    }
  }
`);

export const CREATE_WORKSTREAM = graphql(`
  mutation CreateWorkstream($input: CreateWorkstreamInput!) {
    createWorkstream(input: $input) {
      workstream { id title status model isPinned messageCount createdAt }
    }
  }
`);

export const FORK_WORKSTREAM = graphql(`
  mutation ForkWorkstream($input: ForkWorkstreamInput!) {
    forkWorkstream(input: $input) {
      workstream { id title status model isPinned messageCount createdAt groupId }
      worktrees { directoryPath branch worktreePath error }
    }
  }
`);

export const UPDATE_WORKSTREAM = graphql(`
  mutation UpdateWorkstream($id: ID!, $input: UpdateWorkstreamInput!) {
    updateWorkstream(id: $id, input: $input) {
      workstream { id title status model isPinned updatedAt }
    }
  }
`);

export const ARCHIVE_WORKSTREAM = graphql(`
  mutation ArchiveWorkstream($id: ID!) {
    archiveWorkstream(id: $id) {
      workstream { id status archivedAt updatedAt }
    }
  }
`);

export const UNARCHIVE_WORKSTREAM = graphql(`
  mutation UnarchiveWorkstream($id: ID!) {
    unarchiveWorkstream(id: $id) {
      workstream { id status archivedAt updatedAt }
    }
  }
`);

export const PIN_WORKSTREAM = graphql(`
  mutation PinWorkstream($id: ID!) {
    pinWorkstream(id: $id) {
      workstream { id isPinned }
    }
  }
`);

export const UNPIN_WORKSTREAM = graphql(`
  mutation UnpinWorkstream($id: ID!) {
    unpinWorkstream(id: $id) {
      workstream { id isPinned }
    }
  }
`);

export const DELETE_WORKSTREAM = graphql(`
  mutation DeleteWorkstream($id: ID!) {
    deleteWorkstream(id: $id) {
      workstream { id }
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Generic Entity Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_ENTITY = graphql(`
  query GetEntity($uri: String!) {
    entity(uri: $uri) {
      id
      type
      uri
      title
      description
      createdAt
      updatedAt
    }
  }
`);

export const GET_ENTITIES = graphql(`
  query GetEntities($type: String!, $query: String, $filters: JSON, $limit: Int) {
    entities(type: $type, query: $query, filters: $filters, limit: $limit) {
      id
      type
      uri
      title
      description
      createdAt
      updatedAt
    }
  }
`);

export const SEARCH_ENTITIES = graphql(`
  query SearchEntities($query: String!, $types: [String!], $limit: Int) {
    entitySearch(query: $query, types: $types, limit: $limit) {
      id
      type
      uri
      title
      description
      createdAt
      updatedAt
    }
  }
`);

export const GET_ENTITY_TYPES = graphql(`
  query GetEntityTypes {
    entityTypes {
      type
      displayName
      icon
      source
      uriExample
      display
    }
  }
`);

export const GET_ENTITY_MUTATION_CATALOG = graphql(`
  query GetEntityMutationCatalog {
    entityMutationCatalog {
      entityType
      entityDisplayName
      mutations {
        name
        description
        entityType
      }
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Routine Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_ROUTINES = graphql(`
  query GetRoutines {
    routines {
      id
      name
      description
      workstreamId
      status
      schedule { type expression timezone }
      runCount
      lastRunAt
      nextRunAt
      createdAt
      updatedAt
      latestRun { id status triggeredBy startedAt completedAt }
    }
  }
`);

export const GET_ROUTINES_BY_PROJECT = graphql(`
  query GetRoutinesByProject($projectId: ID!) {
    routinesByProject(projectId: $projectId) {
      id
      name
      description
      workstreamId
      status
      schedule { type expression timezone }
      runCount
      lastRunAt
      nextRunAt
      createdAt
      updatedAt
      latestRun { id status triggeredBy startedAt completedAt }
    }
  }
`);

export const GET_ROUTINE = graphql(`
  query GetRoutine($id: ID!) {
    routine(id: $id) {
      id
      name
      description
      prompt
      workstreamId
      status
      schedule { type expression timezone }
      preferences
      runCount
      lastRunAt
      nextRunAt
      createdAt
      updatedAt
      workstream { id title status }
      latestRun { id status triggeredBy startedAt completedAt summary error }
    }
  }
`);

export const GET_ROUTINE_BY_WORKSTREAM = graphql(`
  query GetRoutineByWorkstream($workstreamId: ID!) {
    routineByWorkstreamId(workstreamId: $workstreamId) {
      id
      name
      description
      prompt
      status
      schedule { type expression timezone }
      runCount
      lastRunAt
      nextRunAt
    }
  }
`);

export const GET_ROUTINE_RUN_HISTORY = graphql(`
  query GetRoutineRunHistory($routineId: ID!, $limit: Int) {
    routineRunHistory(routineId: $routineId, limit: $limit) {
      id
      routineId
      status
      triggeredBy
      startedAt
      completedAt
      summary
      error
      createdAt
    }
  }
`);

export const GET_ROUTINE_LATEST_RUN = graphql(`
  query GetRoutineLatestRun($routineId: ID!) {
    routineLatestRun(routineId: $routineId) {
      id
      status
      triggeredBy
      startedAt
      completedAt
      summary
      error
    }
  }
`);

export const CREATE_ROUTINE = graphql(`
  mutation CreateRoutine($input: CreateRoutineInput!) {
    createRoutine(input: $input) {
      routine {
        id name description prompt workstreamId status
        schedule { type expression timezone }
        runCount createdAt
      }
    }
  }
`);

export const UPDATE_ROUTINE = graphql(`
  mutation UpdateRoutine($id: ID!, $input: UpdateRoutineInput!) {
    updateRoutine(id: $id, input: $input) {
      routine {
        id name description prompt status
        schedule { type expression timezone }
        updatedAt
      }
    }
  }
`);

export const DELETE_ROUTINE = graphql(`
  mutation DeleteRoutine($id: ID!) {
    deleteRoutine(id: $id) {
      routine { id name }
    }
  }
`);

export const PAUSE_ROUTINE = graphql(`
  mutation PauseRoutine($id: ID!) {
    pauseRoutine(id: $id) {
      routine { id status updatedAt }
    }
  }
`);

export const RESUME_ROUTINE = graphql(`
  mutation ResumeRoutine($id: ID!) {
    resumeRoutine(id: $id) {
      routine { id status nextRunAt updatedAt }
    }
  }
`);

export const RUN_ROUTINE_NOW = graphql(`
  mutation RunRoutineNow($id: ID!) {
    runRoutineNow(id: $id) {
      routine {
        id status runCount lastRunAt
        latestRun { id status triggeredBy startedAt completedAt }
      }
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Workstream Agent Operations
// ─────────────────────────────────────────────────────────────────────────────

export const SEND_WORKSTREAM_MESSAGE = graphql(`
  mutation SendWorkstreamMessage($workstreamId: ID!, $text: String!, $imageAttachments: [ImageAttachmentInput!], $imageContentBlocks: [ImageContentBlockInput!]) {
    sendWorkstreamMessage(workstreamId: $workstreamId, text: $text, imageAttachments: $imageAttachments, imageContentBlocks: $imageContentBlocks) {
      workstream { id status messageCount lastActivityAt updatedAt }
    }
  }
`);

export const STOP_WORKSTREAM_AGENT = graphql(`
  mutation StopWorkstreamAgent($id: ID!) {
    stopWorkstreamAgent(id: $id) {
      workstream { id status updatedAt }
    }
  }
`);

export const RESTART_WORKSTREAM_AGENT = graphql(`
  mutation RestartWorkstreamAgent($id: ID!) {
    restartWorkstreamAgent(id: $id) {
      workstream { id status updatedAt }
    }
  }
`);

export const RESPOND_WORKSTREAM_PERMISSION = graphql(`
  mutation RespondWorkstreamPermission($workstreamId: ID!, $requestId: String!, $response: PermissionResponseInput!) {
    respondWorkstreamPermission(workstreamId: $workstreamId, requestId: $requestId, response: $response) {
      workstream { id status updatedAt }
    }
  }
`);

export const REVOKE_PERMISSION_RULE = graphql(`
  mutation RevokePermissionRule($workstreamId: ID!, $toolName: String!, $scope: PermissionRuleScope!) {
    revokePermissionRule(workstreamId: $workstreamId, toolName: $toolName, scope: $scope) {
      workstream { id status updatedAt }
    }
  }
`);

export const INTERRUPT_WORKSTREAM_AGENT = graphql(`
  mutation InterruptWorkstreamAgent($id: ID!) {
    interruptWorkstreamAgent(id: $id) {
      workstream { id status updatedAt }
    }
  }
`);

export const CLEAR_WORKSTREAM_CONVERSATION = graphql(`
  mutation ClearWorkstreamConversation($id: ID!) {
    clearWorkstreamConversation(id: $id) {
      workstream { id status updatedAt }
    }
  }
`);

export const COMPACT_WORKSTREAM_CONVERSATION = graphql(`
  mutation CompactWorkstreamConversation($id: ID!, $instructions: String) {
    compactWorkstreamConversation(id: $id, instructions: $instructions) {
      workstream { id status updatedAt }
    }
  }
`);

export const REWIND_WORKSTREAM_CONVERSATION = graphql(`
  mutation RewindWorkstreamConversation($id: ID!, $eventId: Int!, $role: String) {
    rewindWorkstreamConversation(id: $id, eventId: $eventId, role: $role) {
      workstream { id status updatedAt }
    }
  }
`);

export const SET_WORKSTREAM_IN_FOCUS = graphql(`
  mutation SetWorkstreamInFocus($id: ID) {
    setWorkstreamInFocus(id: $id) {
      workstream { id status updatedAt inFocus }
    }
  }
`);

export const REPLAY_WORKSTREAM_HISTORY = graphql(`
  mutation ReplayWorkstreamHistory($id: ID!) {
    replayWorkstreamHistory(id: $id) {
      workstream { id status updatedAt }
      hasMore
      oldestEventId
    }
  }
`);

export const LOAD_MORE_WORKSTREAM_HISTORY = graphql(`
  mutation LoadMoreWorkstreamHistory($id: ID!, $beforeEventId: Int!, $limit: Int) {
    loadMoreWorkstreamHistory(id: $id, beforeEventId: $beforeEventId, limit: $limit) {
      workstream { id status updatedAt }
      hasMore
      oldestEventId
    }
  }
`);

export const IS_WORKSTREAM_AGENT_RUNNING = graphql(`
  query IsWorkstreamAgentRunning($id: ID!) {
    isWorkstreamAgentRunning(id: $id)
  }
`);

/**
 * Fetch user-sent message history for a workstream (newest first).
 *
 * Used to populate the chat input's up-arrow message history.
 * Supports cursor-based pagination via the `before` argument
 * for preemptive loading as the user navigates backward.
 */
export const GET_USER_MESSAGE_HISTORY = graphql(`
  query GetUserMessageHistory($workstreamId: ID!, $limit: Int, $before: Int) {
    userMessageHistory(workstreamId: $workstreamId, limit: $limit, before: $before) {
      items {
        eventId
        messageId
        text
        timestamp
      }
      hasMore
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Workstream Data Operations (linked entities, directories, model)
// ─────────────────────────────────────────────────────────────────────────────

export const GET_WORKSTREAM_LINKED_ENTITIES = graphql(`
  query GetWorkstreamLinkedEntities($workstreamId: ID!) {
    workstreamLinkedEntities(workstreamId: $workstreamId) {
      workstreamId
      entityUri
      entityType
      entityTitle
      contextOverride
      createdAt
      isInherited
    }
  }
`);

export const GET_WORKSTREAM_DIRECTORIES = graphql(`
  query GetWorkstreamDirectories($workstreamId: ID!) {
    workstreamDirectories(workstreamId: $workstreamId) {
      id
      workstreamId
      path
      label
      isInherited
      createdAt
    }
  }
`);

export const SWITCH_WORKSTREAM_MODEL = graphql(`
  mutation SwitchWorkstreamModel($id: ID!, $model: String!) {
    switchWorkstreamModel(id: $id, model: $model) {
      workstream { id model updatedAt }
    }
  }
`);

export const LINK_WORKSTREAM_ENTITY = graphql(`
  mutation LinkWorkstreamEntity($workstreamId: ID!, $entityUri: String!, $entityType: String!, $entityTitle: String) {
    linkWorkstreamEntity(workstreamId: $workstreamId, entityUri: $entityUri, entityType: $entityType, entityTitle: $entityTitle) {
      workstream { id updatedAt }
    }
  }
`);

export const UNLINK_WORKSTREAM_ENTITY = graphql(`
  mutation UnlinkWorkstreamEntity($workstreamId: ID!, $entityUri: String!) {
    unlinkWorkstreamEntity(workstreamId: $workstreamId, entityUri: $entityUri) {
      workstream { id updatedAt }
    }
  }
`);

export const SET_LINKED_ENTITY_CONTEXT_OVERRIDE = graphql(`
  mutation SetLinkedEntityContextOverride($workstreamId: ID!, $entityUri: String!, $contextOverride: String) {
    setLinkedEntityContextOverride(workstreamId: $workstreamId, entityUri: $entityUri, contextOverride: $contextOverride) {
      workstream { id updatedAt }
    }
  }
`);

// ── Workstream References ────────────────────────────────────────────────────

export const GET_WORKSTREAM_REFERENCES = graphql(`
  query GetWorkstreamReferences($workstreamId: ID!) {
    workstreamReferences(workstreamId: $workstreamId) {
      workstreamId
      entityUri
      entityType
      entityTitle
      externalUrl
      firstReferencedAt
    }
  }
`);

export const ADD_WORKSTREAM_REFERENCE = graphql(`
  mutation AddWorkstreamReference($workstreamId: ID!, $entityUri: String!, $entityType: String!, $entityTitle: String) {
    addWorkstreamReference(workstreamId: $workstreamId, entityUri: $entityUri, entityType: $entityType, entityTitle: $entityTitle) {
      workstream { id updatedAt }
    }
  }
`);

export const REMOVE_WORKSTREAM_REFERENCE = graphql(`
  mutation RemoveWorkstreamReference($workstreamId: ID!, $entityUri: String!) {
    removeWorkstreamReference(workstreamId: $workstreamId, entityUri: $entityUri) {
      workstream { id updatedAt }
    }
  }
`);

export const PROMOTE_WORKSTREAM_REFERENCE = graphql(`
  mutation PromoteWorkstreamReference($workstreamId: ID!, $entityUri: String!, $entityType: String!, $entityTitle: String) {
    promoteWorkstreamReference(workstreamId: $workstreamId, entityUri: $entityUri, entityType: $entityType, entityTitle: $entityTitle) {
      workstream { id updatedAt }
    }
  }
`);

export const GET_WORKSTREAMS_BY_ENTITY = graphql(`
  query GetWorkstreamsByEntity($entityUri: String!) {
    workstreamsByEntity(entityUri: $entityUri) {
      entityUri
      entityType
      entityTitle
      workstreamId
      groupId
      createdAt
      workstream {
        id
        title
        status
        groupId
      }
    }
  }
`);

export const RESOLVE_LINKED_ENTITY_CONTEXT = graphql(`
  query ResolveLinkedEntityContext($entityUri: String!) {
    resolveLinkedEntityContext(entityUri: $entityUri)
  }
`);

export const ENTITY_SEARCH = graphql(`
  query EntitySearch($query: String!, $types: [String!], $limit: Int) {
    entitySearch(query: $query, types: $types, limit: $limit) {
      id
      type
      uri
      title
    }
  }
`);

export const ADD_WORKSTREAM_DIRECTORY = graphql(`
  mutation AddWorkstreamDirectory($workstreamId: ID!, $path: String!, $label: String) {
    addWorkstreamDirectory(workstreamId: $workstreamId, path: $path, label: $label) {
      workstream { id updatedAt }
    }
  }
`);

export const REMOVE_WORKSTREAM_DIRECTORY = graphql(`
  mutation RemoveWorkstreamDirectory($workstreamId: ID!, $path: String!) {
    removeWorkstreamDirectory(workstreamId: $workstreamId, path: $path) {
      workstream { id updatedAt }
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Project Directory Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_PROJECT_DIRECTORIES = graphql(`
  query GetProjectDirectories($projectId: ID!) {
    projectDirectories(projectId: $projectId) {
      id
      projectId
      path
      label
      createdAt
    }
  }
`);

export const ADD_PROJECT_DIRECTORY = graphql(`
  mutation AddProjectDirectory($projectId: ID!, $path: String!, $label: String) {
    addProjectDirectory(projectId: $projectId, path: $path, label: $label) {
      project { id updatedAt }
      directory { id path label createdAt }
    }
  }
`);

export const REMOVE_PROJECT_DIRECTORY = graphql(`
  mutation RemoveProjectDirectory($projectId: ID!, $path: String!) {
    removeProjectDirectory(projectId: $projectId, path: $path) {
      project { id updatedAt }
      removed
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Branch Selection Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_BRANCH_SELECTIONS = graphql(`
  query GetBranchSelections($workstreamId: ID!) {
    branchSelections(workstreamId: $workstreamId) {
      id
      workstreamId
      directoryPath
      branch
      worktreePath
      baseBranch
      createdAt
      updatedAt
    }
  }
`);

export const GET_DIRECTORIES_WITH_BRANCH_INFO = graphql(`
  query GetDirectoriesWithBranchInfo($workstreamId: ID!) {
    directoriesWithBranchInfo(workstreamId: $workstreamId) {
      path
      effectivePath
      label
      branch
      baseBranch
      worktreePath
      isInherited
    }
  }
`);

export const SET_BRANCH_SELECTION = graphql(`
  mutation SetBranchSelection(
    $workstreamId: ID!
    $directoryPath: String!
    $branch: String!
    $worktreePath: String
    $baseBranch: String
    $createWorktree: Boolean
  ) {
    setBranchSelection(
      workstreamId: $workstreamId
      directoryPath: $directoryPath
      branch: $branch
      worktreePath: $worktreePath
      baseBranch: $baseBranch
      createWorktree: $createWorktree
    ) {
      branchSelection {
        id
        directoryPath
        branch
        worktreePath
        baseBranch
        updatedAt
      }
      worktreeError
    }
  }
`);

export const REMOVE_BRANCH_SELECTION = graphql(`
  mutation RemoveBranchSelection($workstreamId: ID!, $directoryPath: String!) {
    removeBranchSelection(workstreamId: $workstreamId, directoryPath: $directoryPath) {
      removed
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Group Directory & Branch Selection Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_GROUP_DIRECTORIES_WITH_BRANCHES = graphql(`
  query GetGroupDirectoriesWithBranches($groupId: ID!) {
    workstreamGroup(id: $groupId) {
      id
      autoCreateWorktrees
      directories {
        id
        path
        label
      }
      branchSelections {
        id
        directoryPath
        branch
        baseBranch
      }
    }
  }
`);

export const ADD_GROUP_DIRECTORY = graphql(`
  mutation AddGroupDirectory($groupId: ID!, $path: String!, $label: String) {
    addGroupDirectory(groupId: $groupId, path: $path, label: $label) {
      group { id }
    }
  }
`);

export const REMOVE_GROUP_DIRECTORY = graphql(`
  mutation RemoveGroupDirectory($groupId: ID!, $path: String!) {
    removeGroupDirectory(groupId: $groupId, path: $path) {
      group { id }
    }
  }
`);

export const SET_GROUP_BRANCH_SELECTION = graphql(`
  mutation SetGroupBranchSelection($groupId: ID!, $directoryPath: String!, $branch: String!, $baseBranch: String) {
    setGroupBranchSelection(groupId: $groupId, directoryPath: $directoryPath, branch: $branch, baseBranch: $baseBranch) {
      group { id }
    }
  }
`);

export const REMOVE_GROUP_BRANCH_SELECTION = graphql(`
  mutation RemoveGroupBranchSelection($groupId: ID!, $directoryPath: String!) {
    removeGroupBranchSelection(groupId: $groupId, directoryPath: $directoryPath) {
      group { id }
    }
  }
`);

export const UPDATE_GROUP_AUTO_CREATE_WORKTREES = graphql(`
  mutation UpdateGroupAutoCreateWorktrees($id: ID!, $autoCreateWorktrees: Boolean!) {
    updateWorkstreamGroup(id: $id, input: { autoCreateWorktrees: $autoCreateWorktrees }) {
      group { id autoCreateWorktrees }
    }
  }
`);

export const ARCHIVE_WORKSTREAM_GROUP = graphql(`
  mutation ArchiveWorkstreamGroup($id: ID!) {
    archiveWorkstreamGroup(id: $id) {
      group { id }
    }
  }
`);

// ─── Group CRUD Operations ──────────────────────────────────────────────────

export const GET_WORKSTREAM_GROUPS_BY_PROJECT = graphql(`
  query GetWorkstreamGroupsByProject($projectId: ID!) {
    workstreamGroupsByProject(projectId: $projectId) {
      id
      name
      emoji
      isPinned
      autoCreateWorktrees
    }
  }
`);

export const CREATE_WORKSTREAM_GROUP = graphql(`
  mutation CreateWorkstreamGroup($input: CreateWorkstreamGroupInput!) {
    createWorkstreamGroup(input: $input) {
      group { id name emoji isPinned }
    }
  }
`);

export const UPDATE_WORKSTREAM_GROUP = graphql(`
  mutation UpdateWorkstreamGroup($id: ID!, $input: UpdateWorkstreamGroupInput!) {
    updateWorkstreamGroup(id: $id, input: $input) {
      group { id name emoji isPinned }
    }
  }
`);

export const PIN_WORKSTREAM_GROUP = graphql(`
  mutation PinWorkstreamGroup($id: ID!) {
    pinWorkstreamGroup(id: $id) {
      group { id isPinned }
    }
  }
`);

export const UNPIN_WORKSTREAM_GROUP = graphql(`
  mutation UnpinWorkstreamGroup($id: ID!) {
    unpinWorkstreamGroup(id: $id) {
      group { id isPinned }
    }
  }
`);

export const DELETE_WORKSTREAM_GROUP = graphql(`
  mutation DeleteWorkstreamGroup($id: ID!) {
    deleteWorkstreamGroup(id: $id) {
      group { id }
    }
  }
`);

export const ADD_WORKSTREAM_TO_GROUP = graphql(`
  mutation AddWorkstreamToGroup($workstreamId: ID!, $groupId: ID!) {
    addWorkstreamToGroup(workstreamId: $workstreamId, groupId: $groupId) {
      workstream { id groupId }
    }
  }
`);

export const REMOVE_WORKSTREAM_FROM_GROUP = graphql(`
  mutation RemoveWorkstreamFromGroup($workstreamId: ID!) {
    removeWorkstreamFromGroup(workstreamId: $workstreamId) {
      workstream { id groupId }
    }
  }
`);

export const LINK_GROUP_ENTITY = graphql(`
  mutation LinkGroupEntity($groupId: ID!, $entityUri: String!, $entityType: String!, $entityTitle: String) {
    linkGroupEntity(groupId: $groupId, entityUri: $entityUri, entityType: $entityType, entityTitle: $entityTitle) {
      group { id }
    }
  }
`);

export const UNLINK_GROUP_ENTITY = graphql(`
  mutation UnlinkGroupEntity($groupId: ID!, $entityUri: String!) {
    unlinkGroupEntity(groupId: $groupId, entityUri: $entityUri) {
      group { id }
    }
  }
`);

export const GET_GROUP_LINKED_ENTITIES = graphql(`
  query GetGroupLinkedEntities($groupId: ID!) {
    groupLinkedEntities(groupId: $groupId) {
      groupId
      entityUri
      entityType
      entityTitle
      contextOverride
      createdAt
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Git Operations
// ─────────────────────────────────────────────────────────────────────────────

export const IS_GIT_REPO = graphql(`
  query IsGitRepo($path: String!) {
    isGitRepo(path: $path)
  }
`);

export const GET_GIT_BRANCHES = graphql(`
  query GetGitBranches($path: String!) {
    gitBranches(path: $path) {
      name
      isCurrent
      isRemote
      hasWorktree
      worktreePath
    }
  }
`);

export const GET_GIT_CURRENT_BRANCH = graphql(`
  query GetGitCurrentBranch($path: String!) {
    gitCurrentBranch(path: $path)
  }
`);

export const GET_GIT_DEFAULT_BRANCH = graphql(`
  query GetGitDefaultBranch($path: String!) {
    gitDefaultBranch(path: $path)
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Git Diff Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_GIT_DIFF_SUMMARY = graphql(`
  query GetGitDiffSummary($path: String!, $base: String!) {
    gitDiffSummary(path: $path, base: $base) {
      additions
      deletions
      files {
        path
        status
        oldPath
        staged
        additions
        deletions
      }
    }
  }
`);

export const GET_GIT_WORKING_TREE_SUMMARY = graphql(`
  query GetGitWorkingTreeSummary($path: String!) {
    gitWorkingTreeSummary(path: $path) {
      additions
      deletions
      files {
        path
        status
        oldPath
        staged
        additions
        deletions
      }
    }
  }
`);

export const GET_GIT_COMMIT_LOG = graphql(`
  query GetGitCommitLog($path: String!, $base: String!) {
    gitCommitLog(path: $path, base: $base) {
      hash
      shortHash
      message
      author
      date
    }
  }
`);

export const GET_GIT_COMMIT_DIFF = graphql(`
  query GetGitCommitDiff($path: String!, $hash: String!) {
    gitCommitDiff(path: $path, hash: $hash)
  }
`);

export const GET_GIT_BRANCH_DIFF = graphql(`
  query GetGitBranchDiff($path: String!, $base: String!) {
    gitBranchDiff(path: $path, base: $base)
  }
`);

export const GET_GIT_WORKING_TREE_DIFF = graphql(`
  query GetGitWorkingTreeDiff($path: String!) {
    gitWorkingTreeDiff(path: $path)
  }
`);

export const GET_GIT_STATUS_FILES = graphql(`
  query GetGitStatusFiles($path: String!) {
    gitStatusFiles(path: $path) {
      path
      status
      oldPath
      staged
      additions
      deletions
    }
  }
`);

export const GET_GIT_FILE_DIFF = graphql(`
  query GetGitFileDiff($path: String!, $filePath: String!, $base: String) {
    gitFileDiff(path: $path, filePath: $filePath, base: $base)
  }
`);

export const GET_GIT_FILE_AT_REF = graphql(`
  query GetGitFileAtRef($path: String!, $filePath: String!, $ref: String) {
    gitFileAtRef(path: $path, filePath: $filePath, ref: $ref)
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Settings Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_SETTINGS = graphql(`
  query GetSettings {
    settings {
      appearance { theme fontSize compactMode zoomLevel }
      ai { defaultModel cliPath cliSetupComplete autoCompactPercent }
      advanced { developerMode focusMonitorEnabled focusMonitorIntervalMs }
      permissions { activePreset rules { tool behavior entityType } }
      notifications { mutedSources mutedTypes }
    }
  }
`);

export const UPDATE_APPEARANCE_SETTINGS = graphql(`
  mutation UpdateAppearanceSettings($input: UpdateAppearanceSettingsInput!) {
    updateAppearanceSettings(input: $input) {
      appearance { theme fontSize compactMode zoomLevel }
      ai { defaultModel cliPath cliSetupComplete autoCompactPercent }
      advanced { developerMode focusMonitorEnabled focusMonitorIntervalMs }
      permissions { activePreset rules { tool behavior entityType } }
      notifications { mutedSources mutedTypes }
    }
  }
`);

export const UPDATE_AI_SETTINGS = graphql(`
  mutation UpdateAiSettings($input: UpdateAiSettingsInput!) {
    updateAiSettings(input: $input) {
      appearance { theme fontSize compactMode zoomLevel }
      ai { defaultModel cliPath cliSetupComplete autoCompactPercent }
      advanced { developerMode focusMonitorEnabled focusMonitorIntervalMs }
      permissions { activePreset rules { tool behavior entityType } }
      notifications { mutedSources mutedTypes }
    }
  }
`);

export const UPDATE_ADVANCED_SETTINGS = graphql(`
  mutation UpdateAdvancedSettings($input: UpdateAdvancedSettingsInput!) {
    updateAdvancedSettings(input: $input) {
      appearance { theme fontSize compactMode zoomLevel }
      ai { defaultModel cliPath cliSetupComplete autoCompactPercent }
      advanced { developerMode focusMonitorEnabled focusMonitorIntervalMs }
      permissions { activePreset rules { tool behavior entityType } }
      notifications { mutedSources mutedTypes }
    }
  }
`);

export const UPDATE_SETTINGS_RAW = graphql(`
  mutation UpdateSettingsRaw($json: String!) {
    updateSettingsRaw(json: $json) {
      appearance { theme fontSize compactMode zoomLevel }
      ai { defaultModel cliPath cliSetupComplete autoCompactPercent }
      advanced { developerMode focusMonitorEnabled focusMonitorIntervalMs }
      permissions { activePreset rules { tool behavior entityType } }
      notifications { mutedSources mutedTypes }
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Notifications Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_NOTIFICATION_SOURCES = graphql(`
  query GetNotificationSources {
    notificationSources {
      source
      muted
      types {
        id
        source
        label
        description
        defaultEnabled
        muted
      }
    }
  }
`);

export const SET_NOTIFICATION_SOURCE_MUTED = graphql(`
  mutation SetNotificationSourceMuted($source: String!, $muted: Boolean!) {
    setNotificationSourceMuted(source: $source, muted: $muted) {
      notifications { mutedSources mutedTypes }
    }
  }
`);

export const SET_NOTIFICATION_TYPE_MUTED = graphql(`
  mutation SetNotificationTypeMuted($typeId: String!, $muted: Boolean!) {
    setNotificationTypeMuted(typeId: $typeId, muted: $muted) {
      notifications { mutedSources mutedTypes }
    }
  }
`);

export const RESET_NOTIFICATION_MUTES = graphql(`
  mutation ResetNotificationMutes {
    resetNotificationMutes {
      notifications { mutedSources mutedTypes }
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Registry Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_REGISTRIES = graphql(`
  query GetRegistries {
    registries {
      id
      name
      url
      enabled
      priority
      source
      createdAt
      updatedAt
    }
  }
`);

export const GET_REGISTRY = graphql(`
  query GetRegistry($id: ID!) {
    registry(id: $id) {
      id
      name
      url
      enabled
      priority
      source
      createdAt
      updatedAt
    }
  }
`);

export const GET_REGISTRY_QUICK_ACTIONS = graphql(`
  query GetRegistryQuickActions {
    registryQuickActions {
      id
      label
      icon
      description
      author { name }
      tags
      registry
      options { id label prompt }
    }
  }
`);

export const GET_REGISTRY_QUICK_ACTION_DEFAULTS = graphql(`
  query GetRegistryQuickActionDefaults {
    registryQuickActionDefaults
  }
`);

export const GET_REGISTRY_VERIFICATION_ACTIONS = graphql(`
  query GetRegistryVerificationActions {
    registryVerificationActions {
      id
      type
      label
      builtinId
      prompt
    }
  }
`);

export const GET_REGISTRY_VERIFICATION_ACTION_DEFAULTS = graphql(`
  query GetRegistryVerificationActionDefaults {
    registryVerificationActionDefaults {
      id
      type
      label
      builtinId
      prompt
    }
  }
`);

export const ADD_REGISTRY = graphql(`
  mutation AddRegistry($input: AddRegistryInput!) {
    addRegistry(input: $input) {
      registry {
        id name url enabled priority source createdAt updatedAt
      }
    }
  }
`);

export const REMOVE_REGISTRY = graphql(`
  mutation RemoveRegistry($id: ID!) {
    removeRegistry(id: $id) {
      registry { id name }
    }
  }
`);

export const UPDATE_REGISTRY = graphql(`
  mutation UpdateRegistry($id: ID!, $input: UpdateRegistryInput!) {
    updateRegistry(id: $id, input: $input) {
      registry {
        id name url enabled priority updatedAt
      }
    }
  }
`);

export const SYNC_REGISTRIES = graphql(`
  mutation SyncRegistries {
    syncRegistries {
      synced
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Skills Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_INSTALLED_SKILLS = graphql(`
  query GetInstalledSkills {
    installedSkills {
      id name description version registryVersion
      source sourceRef registry path
      icon category tags author
      enabled pinned installDate lastUsed useCount
      hasUpdate
    }
  }
`);

export const GET_REGISTRY_SKILLS = graphql(`
  query GetRegistrySkills {
    registrySkills {
      id name description version
      source repo icon category tags
      author { name }
      registry
    }
  }
`);

export const INSTALL_SKILL = graphql(`
  mutation InstallSkill($skillId: String!, $destination: String) {
    installSkill(skillId: $skillId, destination: $destination) {
      skill {
        id name description version registryVersion
        source sourceRef registry path
        icon category tags author
        enabled pinned installDate lastUsed useCount
        hasUpdate
      }
    }
  }
`);

export const UNINSTALL_SKILL = graphql(`
  mutation UninstallSkill($skillId: String!) {
    uninstallSkill(skillId: $skillId) {
      success
    }
  }
`);

export const UPDATE_SKILL = graphql(`
  mutation UpdateSkill($skillId: String!) {
    updateSkill(skillId: $skillId) {
      skill {
        id name description version registryVersion
        source sourceRef registry path
        icon category tags author
        enabled pinned installDate lastUsed useCount
        hasUpdate
      }
    }
  }
`);

export const ACTIVATE_SKILL = graphql(`
  mutation ActivateSkill($skillId: String!) {
    activateSkill(skillId: $skillId) {
      body
    }
  }
`);

export const TOGGLE_SKILL_ENABLED = graphql(`
  mutation ToggleSkillEnabled($skillId: String!, $enabled: Boolean!) {
    toggleSkillEnabled(skillId: $skillId, enabled: $enabled) {
      skill {
        id enabled
      }
    }
  }
`);

export const TOGGLE_SKILL_PINNED = graphql(`
  mutation ToggleSkillPinned($skillId: String!, $pinned: Boolean!) {
    toggleSkillPinned(skillId: $skillId, pinned: $pinned) {
      skill {
        id pinned
      }
    }
  }
`);

export const SYNC_LOCAL_SKILLS = graphql(`
  mutation SyncLocalSkills {
    syncLocalSkills
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Plugin Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_INSTALLED_PLUGINS = graphql(`
  query GetInstalledPlugins {
    installedPlugins {
      id name description version registryVersion
      source sourceRef registry path
      icon category tags author
      enabled installDate
      hasUpdate
    }
  }
`);

export const GET_REGISTRY_PLUGINS = graphql(`
  query GetRegistryPlugins {
    registryPlugins {
      id name description version
      source repo icon category tags
      author { name }
      registry
      canvases { navSidebar drawer menuBar feed }
    }
  }
`);

export const INSTALL_PLUGIN = graphql(`
  mutation InstallPlugin($pluginId: String!) {
    installPlugin(pluginId: $pluginId) {
      plugin {
        id name description version registryVersion
        source sourceRef registry path
        icon category tags author
        enabled installDate
        hasUpdate
      }
    }
  }
`);

export const UNINSTALL_PLUGIN = graphql(`
  mutation UninstallPlugin($pluginId: String!) {
    uninstallPlugin(pluginId: $pluginId) {
      success
    }
  }
`);

export const UPDATE_PLUGIN = graphql(`
  mutation UpdatePlugin($pluginId: String!) {
    updatePlugin(pluginId: $pluginId) {
      plugin {
        id name description version registryVersion
        source sourceRef registry path
        icon category tags author
        enabled installDate
        hasUpdate
      }
    }
  }
`);

export const TOGGLE_PLUGIN_ENABLED = graphql(`
  mutation TogglePluginEnabled($pluginId: String!, $enabled: Boolean!) {
    togglePluginEnabled(pluginId: $pluginId, enabled: $enabled) {
      plugin {
        id enabled
      }
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Command Palette Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_COMMANDS = graphql(`
  query GetCommands($categoryFilter: String) {
    commands(categoryFilter: $categoryFilter) {
      id
      category
      title
      description
      keywords
      disabled
      disabledReason
      hasFlow
      body
    }
  }
`);

export const EXECUTE_COMMAND = graphql(`
  mutation ExecuteCommand($commandId: String!, $args: JSON) {
    executeCommand(commandId: $commandId, args: $args) {
      success
      error
      action {
        type
        path
        message
        variant
        text
      }
    }
  }
`);

export const RESCAN_CLAUDE_COMMANDS = graphql(`
  mutation RescanClaudeCommands {
    rescanClaudeCommands
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Permission Policy Operations
// ─────────────────────────────────────────────────────────────────────────────

export const UPDATE_PERMISSIONS_SETTINGS = graphql(`
  mutation UpdatePermissionsSettings($input: UpdatePermissionsSettingsInput!) {
    updatePermissionsSettings(input: $input) {
      appearance { theme fontSize compactMode zoomLevel }
      ai { defaultModel cliPath cliSetupComplete autoCompactPercent }
      advanced { developerMode focusMonitorEnabled focusMonitorIntervalMs }
      permissions { activePreset rules { tool behavior entityType } }
      notifications { mutedSources mutedTypes }
    }
  }
`);

export const GET_PERMISSION_POLICY = graphql(`
  query GetPermissionPolicy($scopeType: PermissionScopeType!, $scopeId: String!) {
    permissionPolicy(scopeType: $scopeType, scopeId: $scopeId) {
      id
      scopeType
      scopeId
      rules { tool behavior entityType }
      templateId
      createdAt
      updatedAt
    }
  }
`);

export const SET_PERMISSION_POLICY = graphql(`
  mutation SetPermissionPolicy($scopeType: PermissionScopeType!, $scopeId: String!, $rules: [PermissionRuleConfigInput!]!) {
    setPermissionPolicy(scopeType: $scopeType, scopeId: $scopeId, rules: $rules) {
      id
      scopeType
      scopeId
      rules { tool behavior entityType }
      templateId
    }
  }
`);

export const DELETE_PERMISSION_POLICY = graphql(`
  mutation DeletePermissionPolicy($scopeType: PermissionScopeType!, $scopeId: String!) {
    deletePermissionPolicy(scopeType: $scopeType, scopeId: $scopeId)
  }
`);

export const GET_RESOLVED_PERMISSIONS = graphql(`
  query GetResolvedPermissions($workstreamId: ID!) {
    resolvedPermissions(workstreamId: $workstreamId) {
      tool
      behavior
      entityType
    }
  }
`);

export const GET_RESOLVED_PARENT_PERMISSIONS = graphql(`
  query GetResolvedParentPermissions($scopeType: PermissionScopeType!, $scopeId: String!) {
    resolvedParentPermissions(scopeType: $scopeType, scopeId: $scopeId) {
      tool
      behavior
      entityType
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Permission Template Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_PERMISSION_TEMPLATES = graphql(`
  query GetPermissionTemplates {
    permissionTemplates {
      id
      name
      description
      rules { tool behavior entityType }
      createdAt
      updatedAt
    }
  }
`);

export const GET_PERMISSION_TEMPLATE = graphql(`
  query GetPermissionTemplate($id: ID!) {
    permissionTemplate(id: $id) {
      id
      name
      description
      rules { tool behavior entityType }
      createdAt
      updatedAt
    }
  }
`);

export const CREATE_PERMISSION_TEMPLATE = graphql(`
  mutation CreatePermissionTemplate($name: String!, $description: String, $rules: [PermissionRuleConfigInput!]!) {
    createPermissionTemplate(name: $name, description: $description, rules: $rules) {
      id
      name
      description
      rules { tool behavior entityType }
      createdAt
      updatedAt
    }
  }
`);

export const UPDATE_PERMISSION_TEMPLATE = graphql(`
  mutation UpdatePermissionTemplate($id: ID!, $name: String, $description: String, $rules: [PermissionRuleConfigInput!]) {
    updatePermissionTemplate(id: $id, name: $name, description: $description, rules: $rules) {
      id
      name
      description
      rules { tool behavior entityType }
      createdAt
      updatedAt
    }
  }
`);

export const DELETE_PERMISSION_TEMPLATE = graphql(`
  mutation DeletePermissionTemplate($id: ID!) {
    deletePermissionTemplate(id: $id)
  }
`);

export const APPLY_PERMISSION_TEMPLATE = graphql(`
  mutation ApplyPermissionTemplate($templateId: ID!, $scopeType: PermissionScopeType!, $scopeId: String!) {
    applyPermissionTemplate(templateId: $templateId, scopeType: $scopeType, scopeId: $scopeId)
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Tag Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_TAGS_BY_PROJECT = graphql(`
  query GetTagsByProject($projectId: ID!) {
    tagsByProject(projectId: $projectId) {
      name
      instructions
      color
      maxDepth
      spawnWorkstream
      worktreeMode
      dependsOn
    }
  }
`);

export const GET_TAG_BY_NAME = graphql(`
  query GetTagByName($projectId: ID!, $name: String!) {
    tagByName(projectId: $projectId, name: $name) {
      name
      instructions
      color
      maxDepth
      spawnWorkstream
      worktreeMode
      dependsOn
    }
  }
`);

export const GET_WORKSTREAM_TAGS = graphql(`
  query GetWorkstreamTags($workstreamId: ID!) {
    workstreamTags(workstreamId: $workstreamId) {
      id
      workstreamId
      tagName
      tagInstructions
      tagColor
      tagMaxDepth
      tagSpawnWorkstream
      tagWorktreeMode
      tagDependsOn
      status
      appliedAt
      startedAt
      completedAt
      error
      appliedBy
      depth
      delegatedWorkstreamId
    }
  }
`);

export const CREATE_TAG = graphql(`
  mutation CreateTag($input: CreateTagInput!) {
    createTag(input: $input) {
      tag {
        name
        instructions
        color
        maxDepth
        spawnWorkstream
        worktreeMode
        dependsOn
      }
    }
  }
`);

export const UPDATE_TAG = graphql(`
  mutation UpdateTag($projectId: ID!, $tagName: String!, $input: UpdateTagInput!) {
    updateTag(projectId: $projectId, tagName: $tagName, input: $input) {
      tag {
        name
        instructions
        color
        maxDepth
        spawnWorkstream
        worktreeMode
        dependsOn
      }
    }
  }
`);

export const DELETE_TAG = graphql(`
  mutation DeleteTag($projectId: ID!, $tagName: String!) {
    deleteTag(projectId: $projectId, tagName: $tagName) {
      tag {
        name
      }
    }
  }
`);

export const APPLY_TAG_TO_WORKSTREAM = graphql(`
  mutation ApplyTagToWorkstream($workstreamId: ID!, $tagName: String!) {
    applyTagToWorkstream(workstreamId: $workstreamId, tagName: $tagName) {
      workstreamTag {
        id
        workstreamId
        tagName
        tagColor
        status
        appliedAt
        appliedBy
        depth
      }
      pipelineRunId
    }
  }
`);

export const REMOVE_TAG_FROM_WORKSTREAM = graphql(`
  mutation RemoveTagFromWorkstream($workstreamId: ID!, $tagName: String!) {
    removeTagFromWorkstream(workstreamId: $workstreamId, tagName: $tagName) {
      success
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Content Profiles
// ─────────────────────────────────────────────────────────────────────────────

export const GET_CONTENT_PROFILES = graphql(`
  query GetContentProfiles {
    contentProfiles {
      name
      directory
      isDefault
      isActive
      isFork
      metadata {
        displayName
        description
        author {
          name
          url
        }
        icon
        tags
        sourceUrl
      }
    }
  }
`);

export const GET_ACTIVE_CONTENT_PROFILE = graphql(`
  query GetActiveContentProfile {
    activeContentProfile {
      name
      directory
      isDefault
      isActive
      isFork
      metadata {
        displayName
        description
        icon
        tags
        sourceUrl
      }
    }
  }
`);

export const FORK_CONTENT_PROFILE = graphql(`
  mutation ForkContentProfile($gitUrl: String!, $name: String) {
    forkContentProfile(gitUrl: $gitUrl, name: $name) {
      name
      directory
      isDefault
      isActive
      isFork
      metadata {
        displayName
        description
        icon
        sourceUrl
      }
    }
  }
`);

export const SWITCH_CONTENT_PROFILE = graphql(`
  mutation SwitchContentProfile($name: String!) {
    switchContentProfile(name: $name)
  }
`);

export const DELETE_CONTENT_PROFILE = graphql(`
  mutation DeleteContentProfile($name: String!) {
    deleteContentProfile(name: $name)
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Task Operations
// ─────────────────────────────────────────────────────────────────────────────

export const GET_TASK = graphql(`
  query GetTask($id: ID!) {
    task(id: $id) {
      id
      projectId
      identifier
      title
      description
      status
      priority
      assigneeType
      assigneeWorkstreamId
      dueDate
      parentId
      links
      createdAt
      updatedAt
      labels {
        id
        name
        color
      }
      subtasks {
        id
        identifier
        title
        status
        priority
      }
      parent {
        id
        identifier
        title
      }
    }
  }
`);

export const GET_TASKS = graphql(`
  query GetTasks($projectId: ID!, $status: TaskStatus, $priority: TaskPriority, $assigneeType: TaskAssigneeType, $labelId: String, $parentId: String, $query: String, $limit: Int) {
    tasks(projectId: $projectId, status: $status, priority: $priority, assigneeType: $assigneeType, labelId: $labelId, parentId: $parentId, query: $query, limit: $limit) {
      id
      projectId
      identifier
      title
      description
      status
      priority
      assigneeType
      assigneeWorkstreamId
      dueDate
      parentId
      links
      createdAt
      updatedAt
      labels {
        id
        name
        color
      }
    }
  }
`);

export const GET_TASK_LABELS = graphql(`
  query GetTaskLabels($projectId: ID!) {
    taskLabels(projectId: $projectId) {
      id
      projectId
      name
      color
      createdAt
    }
  }
`);

export const CREATE_TASK = graphql(`
  mutation CreateTask($input: CreateTaskInput!) {
    createTask(input: $input) {
      task {
        id
        projectId
        identifier
        title
        status
        priority
        createdAt
      }
    }
  }
`);

export const UPDATE_TASK = graphql(`
  mutation UpdateTask($id: ID!, $input: UpdateTaskInput!) {
    updateTask(id: $id, input: $input) {
      task {
        id
        projectId
        identifier
        title
        description
        status
        priority
        assigneeType
        assigneeWorkstreamId
        dueDate
        parentId
        links
        createdAt
        updatedAt
        labels {
          id
          name
          color
        }
      }
    }
  }
`);

export const DELETE_TASK = graphql(`
  mutation DeleteTask($id: ID!) {
    deleteTask(id: $id) {
      success
    }
  }
`);

export const CREATE_TASK_LABEL = graphql(`
  mutation CreateTaskLabel($projectId: ID!, $name: String!, $color: String!) {
    createTaskLabel(projectId: $projectId, name: $name, color: $color) {
      label {
        id
        projectId
        name
        color
        createdAt
      }
    }
  }
`);

export const UPDATE_TASK_LABEL = graphql(`
  mutation UpdateTaskLabel($id: ID!, $name: String, $color: String) {
    updateTaskLabel(id: $id, name: $name, color: $color) {
      label {
        id
        projectId
        name
        color
        createdAt
      }
    }
  }
`);

export const DELETE_TASK_LABEL = graphql(`
  mutation DeleteTaskLabel($id: ID!) {
    deleteTaskLabel(id: $id) {
      success
    }
  }
`);

// ── Inbox ───────────────────────────────────────────────────────────────────

export const GET_INBOX_ITEMS = graphql(`
  query GetInboxItems($includeArchived: Boolean, $includeRead: Boolean, $limit: Int, $offset: Int) {
    inboxItems(includeArchived: $includeArchived, includeRead: $includeRead, limit: $limit, offset: $offset) {
      id
      title
      description
      icon
      source
      actions {
        id
        label
        payload
      }
      entityUri
      ctaLabel
      read
      archived
      createdAt
      updatedAt
    }
  }
`);

export const GET_INBOX_UNREAD_COUNT = graphql(`
  query GetInboxUnreadCount {
    inboxUnreadCount
  }
`);

export const PUSH_INBOX_ITEM = graphql(`
  mutation PushInboxItem($input: PushInboxItemInput!) {
    pushInboxItem(input: $input) {
      inboxItem {
        id
        title
        description
        icon
        source
        actions {
          id
          label
          payload
        }
        entityUri
        ctaLabel
        read
        archived
        createdAt
        updatedAt
      }
    }
  }
`);

export const MARK_INBOX_ITEM_READ = graphql(`
  mutation MarkInboxItemRead($id: ID!) {
    markInboxItemRead(id: $id) {
      inboxItem {
        id
        read
      }
    }
  }
`);

export const MARK_ALL_INBOX_ITEMS_READ = graphql(`
  mutation MarkAllInboxItemsRead {
    markAllInboxItemsRead {
      count
    }
  }
`);

export const ARCHIVE_INBOX_ITEM = graphql(`
  mutation ArchiveInboxItem($id: ID!) {
    archiveInboxItem(id: $id) {
      inboxItem {
        id
        archived
      }
    }
  }
`);

export const DELETE_INBOX_ITEM = graphql(`
  mutation DeleteInboxItem($id: ID!) {
    deleteInboxItem(id: $id) {
      success
    }
  }
`);

export const EXECUTE_INBOX_ACTION = graphql(`
  mutation ExecuteInboxAction($actionId: String!, $payload: JSON) {
    executeInboxAction(actionId: $actionId, payload: $payload) {
      success
    }
  }
`);

// ── Events ──────────────────────────────────────────────────────────────────

export const GET_REGISTERED_EVENTS = graphql(`
  query GetRegisteredEvents {
    registeredEvents {
      qualifiedName
      localName
      description
      ownerPluginId
      listenerCount
      payloadSchema
    }
  }
`);

// ─────────────────────────────────────────────────────────────────────────────
// Entity Tool Operations (dev debugging)
// ─────────────────────────────────────────────────────────────────────────────

export const GET_ENTITY_TOOL_ENTRIES = graphql(`
  query GetEntityToolEntries {
    entityToolEntries {
      uri
      addedAt
    }
  }
`);

export const ADD_ENTITY_TOOL_ENTRY = graphql(`
  mutation AddEntityToolEntry($uri: String!) {
    addEntityToolEntry(uri: $uri) {
      entry {
        uri
        addedAt
      }
      alreadyExists
    }
  }
`);

export const REMOVE_ENTITY_TOOL_ENTRY = graphql(`
  mutation RemoveEntityToolEntry($uri: String!) {
    removeEntityToolEntry(uri: $uri) {
      success
    }
  }
`);
